### ISSUE TITLE
 Release the complete code

### ISSUE THREAD

**Issue by AndSonder** [SmartEngines/hough_document_localization#1]
Your repo seems only released the codes about test. Could you relase the complete code?

**Comment by kbulatov** [comment]
Hi! Thank you for your interest. The repo contains the scripts required to reproduct the metrics employed in the article in order to compare the results with the same methodology. The description of the method is given in the article (http://www.computeroptics.ru/KO/PDF/KO45-5/450509.pdf), but the code of the system is proprietary and thus is not released.
